[
  ./apps.nix
  ./darwin.nix
  ./home-apps.nix
  ./home.nix
  ./hosts.nix
  ./modules.nix
  ./nixos.nix
  ./nixpkgs.nix
  ./tags.nix
  ./apps/defaults.nix
  ./apps/desktop.nix
  ./apps/desktop/sway.nix
  ./apps/desktop/waybar.nix
  ./apps/desktop/hyprland.nix
  ./apps/development.nix
  ./apps/disko.nix
  ./apps/gaming.nix
  ./apps/home-manager.nix
  ./apps/nvidia.nix
  ./apps/qemu.nix
  ./apps/server.nix
  ./apps/single-user.nix
  ./apps/sysadmin.nix
]
