keys:
  - &admin_ion 956F38534AA3E67292A94A3FA239E341B9CB8257
  - &server_xeus age1gvlejzqth4h4hs0eqwxgpt23673ufpwlnmlz0p0fm3q29anvcexs56xk67
creation_rules:
  - path_regex: secrets/shared/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
          - *admin_ion
        age:
          - *server_xeus
  - path_regex: secrets/xeus\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
          - *admin_ion
        age:
          - *server_xeus
